// Generated by solid-link (@solidjs/blocks-linker) from this project's render sites.
// Do not edit; commit it. The Vite plugin regenerates it on save; `solid-link --check`
// fails when it is stale. pending / fails color the prop's reads (TypedProps<P, "Key">);
// live / static are facts for tools (a compiler may treat a static prop as inert).
// schema: solid-blocks-summary v1
export {};
declare module "@solidjs/blocks" {
  interface PropColors {
    "ActivityLine": {
      activity: { pending: true; fails: import("./lib/errors").LiveError; live: true; static: false };
    };
    "Archive": {
      room: { pending: false; fails: never; live: true; static: false };
    };
    "ArchiveCount": {
      stats: { pending: true; fails: import("./lib/errors").ArchiveError; live: true; static: false };
    };
    "Card": {
      room: { pending: false; fails: never; live: true; static: false };
    };
    "CardBody": {
      activity: { pending: true; fails: import("./lib/errors").LiveError; live: true; static: false };
      card: { pending: false; fails: never; live: true; static: false };
      members: { pending: true; fails: import("./lib/errors").LiveError; live: true; static: false };
    };
    "Chat": {
      room: { pending: false; fails: never; live: true; static: false };
    };
    "Composer": {
      error: { pending: false; fails: never; live: true; static: false };
      post: { pending: false; fails: never; live: true; static: false };
      room: { pending: false; fails: never; live: true; static: false };
      sending: { pending: false; fails: never; live: true; static: false };
    };
    "Count": {
      who: { pending: true; fails: import("./lib/errors").LiveError; live: true; static: false };
    };
    "Directory": {
      current: { pending: false; fails: never; live: true; static: false };
    };
    "DirectoryEntry": {
      current: { pending: false; fails: never; live: true; static: false };
      name: { pending: false; fails: never; live: true; static: false };
    };
    "Header": {
      room: { pending: false; fails: never; live: true; static: false };
    };
    "IdentityProvider": {
      children: { pending: false; fails: never; live: true; static: false };
    };
    "Joined": {
      joined: { pending: true; fails: import("./lib/errors").LiveError; live: true; static: false };
      me: { pending: false; fails: never; live: true; static: false };
    };
    "LivePage": {
      room: { pending: false; fails: never; live: true; static: false };
    };
    "MemberCount": {
      members: { pending: true; fails: import("./lib/errors").LiveError; live: true; static: false };
    };
    "Members": {
      me: { pending: false; fails: never; live: true; static: false };
      who: { pending: true; fails: import("./lib/errors").LiveError; live: true; static: false };
    };
    "Messages": {
      messages: { pending: false; fails: never; live: true; static: false };
    };
    "StatusPill": {
      label: { pending: false; fails: never; live: false; static: true };
      wire: { pending: false; fails: never; live: true; static: false };
    };
    "Summary": {
      room: { pending: false; fails: never; live: true; static: false };
    };
    "SummaryText": {
      attempt: { pending: false; fails: never; live: true; static: false };
      room: { pending: false; fails: never; live: true; static: false };
    };
    "Transcript": {
      messages: { pending: false; fails: never; live: true; static: false };
      wire: { pending: false; fails: never; live: true; static: false };
    };
  }
}
