export {
  $REFRESH,
  ContextNotFoundError,
  NoOwnerError,
  NotReadyError,
  TimeoutError,
  action,
  syncAction,
  createContext,
  createOwner,
  createRoot,
  runWithOwner,
  flush,
  getNextChildId,
  peekNextChildId,
  getContext,
  setContext,
  getOwner,
  isDisposed,
  getObserver,
  isEqual,
  untrack,
  isPending,
  latest,
  SUPPORTS_PROXY,
  setSnapshotCapture,
  markSnapshotScope,
  releaseSnapshotScope,
  clearSnapshots,
  enforceLoadingBoundary,
  enableExternalSource,
  resetErrorHalt,
  statusFree,
  iterateContext,
  configureClientErrors,
  ROOT_ERROR_HOOK
} from "./core/index.js";
/**
 * @internal The dev console footer seam — registered by `solid-js`, which
 * owns the repair skill the footer points at. Not part of `DEV`; a no-op
 * outside dev builds.
 */
export { setConsoleFooter } from "./core/index.js";
import { DEV as _DEV, OBSERVE as _OBSERVE, type Dev, type Observe } from "./core/index.js";
/**
 * Observe tier (diagnostics channel, attribution hook slot + interaction
 * frame): dev and observe builds. The attribution engine itself is the
 * `@solidjs/signals/attribution` entry.
 */
export const OBSERVE: Observe | undefined = __OBSERVE__ ? _OBSERVE : undefined;
/** Dev tier (devtools hooks, graph traversal, console reporting): dev builds only. */
export const DEV: Dev | undefined = __DEV__ ? _DEV : undefined;
export type {
  Owner,
  Context,
  ContextRecord,
  ContextIterable,
  IQueue,
  ExternalSourceFactory,
  ExternalSource,
  ExternalSourceConfig,
  Refreshable,
  AttributionSlot,
  ClientErrorContext,
  ClientErrorHook,
  ClientErrorsConfig,
  InteractionRef,
  NavigationRef,
  Dev,
  Observe,
  ServerObserve,
  Records,
  RecordTypes,
  HostRecordTypes,
  RecordType,
  RecordEvent,
  RecordLive,
  RecordListener,
  RecordSubscribeOptions,
  DevHooks,
  DiagnosticCapture,
  DiagnosticCode,
  DiagnosticEvent,
  DiagnosticKind,
  DiagnosticListener,
  Diagnostics,
  DiagnosticSeverity,
  DiagnosticSubject
} from "./core/index.js";
export {
  createSignal,
  createMemo,
  createEffect,
  createRenderEffect,
  createTrackedEffect,
  createReaction,
  createOptimistic,
  refresh,
  resolve,
  until,
  onSettled,
  onCleanup,
  syncOnly,
  generatorMemo,
  generatorEffect,
  renderCallback,
  SCOPE_CALLBACK
} from "./signals.js";
export {
  $,
  raise,
  attempt,
  readStore,
  readPath,
  readPath1,
  readPath2,
  readPath3,
  readPath4,
  readPathN,
  readHandle1,
  readHandle2,
  readHandle3,
  readHandle4,
  readHandleN,
  readHandleChild,
  readBorrowed,
  markHandle,
  readProp,
  readValue,
  perform,
  blockFlags,
  BLOCK_SYNC,
  BLOCK_NOTHROW,
  BLOCK_STATIC,
  isBlock,
  outsideBlock,
  inBlock,
  blockScope,
  syncBlock,
  blockCleanup,
  asyncBody,
  AsyncRun,
  EventRun,
  readAccessor,
  readSelected,
  installBlockDriver
} from "./generator.js";
// Renderer entry points: forwarders the block runtime fills when the first
// block is built (block-hooks.ts), so renderers do not retain it.
export { lazyView, renderBlock, dispatchBlock } from "./block-hooks.js";
export {
  $component,
  $memo,
  $effect,
  $settled,
  settledBlock,
  $event,
  $signal,
  $store,
  $cleanup,
  $flush,
  effectBlock,
  isComponent,
  setBlockPrimitives,
  $componentCompiled,
  $scope,
  $scopeCompiled,
  $eventCompiled,
  $eventAsync,
  effectBlockCompiled,
  settledBlockCompiled,
  withReceipts,
  readContext
} from "./block-api.js";
export type {
  View,
  SettledView,
  NonView,
  ViewOf,
  TypedProps,
  PropPath,
  GeneratorBody,
  GeneratorYield,
  GeneratorReturn,
  TypedStore,
  StoreSource,
  PropsInput,
  ScopeBody,
  Component as BlockComponent,
  BlockSetter,
  BlockStoreSetter,
  WriteReceipt,
  MemoAccessor,
  EventHandler,
  SetupOp,
  MemoOp,
  EffectOp,
  EventOp,
  ViewOp
} from "./block-api.js";
export type { CreateOp, CleanupOp, ContextOp, FlushOp } from "./generator.js";
export type {
  Block,
  AnyBlock,
  BlockAccessor,
  BlockMetadata,
  ColoredAccessor,
  BlockMeta,
  BlockValue,
  BlockReads,
  BlockTasks,
  BlockFailures,
  BlockWrites,
  BlockInput,
  BlockOps,
  BlockAsync,
  BlockErrors,
  ReadsOf,
  TasksOf,
  FailuresOf,
  WritesOf,
  ReactiveHostBlock,
  JsxBlock,
  JsxBlockShape,
  EventBlock,
  StrictCallback,
  ErrorClass,
  AnySetter,
  Op,
  ReadOp,
  StoreReadOp,
  StoreRead,
  PropRead,
  PathKey,
  PathValue,
  PathResult,
  ReadThrough,
  StoreHandle,
  Borrowed,
  AsyncOp,
  RaiseOp,
  AttemptOp,
  WriteOp,
  CallOp
} from "./generator.js";
export { loading, errored } from "./blocks.js";
export type {
  Truthy,
  UntilOptions,
  Accessor,
  AccessorIterable,
  SourceAccessor,
  Setter,
  Signal,
  BlockSignal,
  ComputeFunction,
  EffectFunction,
  EffectBundle,
  EffectOptions,
  SignalOptions,
  MemoOptions,
  NoInfer
} from "./signals.js";
export { affects } from "./affects.js";
export { mapArray, repeat, type Maybe } from "./map.js";
export * from "./store/index.js";
export {
  createLoadingBoundary,
  createErrorBoundary,
  createRevealOrder,
  flatten,
  isReadOp,
  type RevealOrder
} from "./boundaries.js";
