import type { ClientHydrationManifest } from "./schema.js";
import { assertHydrationManifest } from "./validate.js";

/** One runtime export a capability installs through. */
export interface CapabilityInstaller {
  /** Module specifier the export is imported from. */
  module: string;
  /** Export name: a function taking no arguments, run at hydrate() time. */
  name: string;
}

/**
 * Consumers for capabilities that have no built-in runtime consumer yet
 * (today only the reserved `resumableEvents`). Registering one is how a
 * future slice plugs its bootstrap into composed entries without changing
 * the manifest schema.
 */
export interface CapabilityConsumers {
  resumableEvents?: CapabilityInstaller;
}

export interface ComposeOptions {
  /** Specifier for the reactive library. Default "solid-js". */
  solidModule?: string;
  /** Specifier for the DOM runtime. Default "@solidjs/web". */
  webModule?: string;
  consumers?: CapabilityConsumers;
}

/**
 * The installers a manifest selects, in the canonical order the universal
 * hydrate() also installs them. This table is the consumption contract: it
 * maps each manifest capability to the runtime export that installs it.
 */
export function resolveHydrationInstallers(
  manifest: ClientHydrationManifest,
  options: ComposeOptions = {}
): CapabilityInstaller[] {
  const solid = options.solidModule ?? "solid-js";
  const web = options.webModule ?? "@solidjs/web";
  const c = manifest.capabilities;
  const out: CapabilityInstaller[] = [];
  if (c.snapshots) out.push({ module: solid, name: "installSnapshotHydration" });
  if (c.asyncResults) out.push({ module: solid, name: "installAsyncResultHydration" });
  if (c.ssrSources.includes("client"))
    out.push({ module: solid, name: "installSsrClientHydration" });
  if (c.ssrSources.includes("hybrid"))
    out.push({ module: solid, name: "installSsrHybridHydration" });
  if (c.storeAdapters) out.push({ module: solid, name: "installStoreHydration" });
  if (c.errorMarkers) out.push({ module: solid, name: "installErrorMarkerHydration" });
  if (c.loadingMarkers) out.push({ module: web, name: "loadingMarkerHydration" });
  if (c.streamLedger) out.push({ module: web, name: "streamLedgerHydration" });
  if (c.lazyAssets) out.push({ module: web, name: "lazyAssetHydration" });
  if (c.delegatedEvents.length) out.push({ module: web, name: "eventReplayHydration" });
  if (c.resumableEvents) out.push(options.consumers!.resumableEvents!);
  return out;
}

/**
 * Compose the client hydration entry for a manifest: a module exporting a
 * `hydrate` that installs exactly the manifest's capabilities. The output is
 * deterministic (same manifest and options → same bytes), so it can be
 * cached, diffed, and served as a virtual module by a bundler plugin.
 *
 * Only this generated module chooses capabilities; application code imports
 * `hydrate` from it instead of from `@solidjs/web`.
 */
export function composeHydrationEntry(
  manifest: ClientHydrationManifest,
  options: ComposeOptions = {}
): string {
  assertHydrationManifest(manifest, { consumers: options.consumers });
  const web = options.webModule ?? "@solidjs/web";
  const installers = resolveHydrationInstallers(manifest, options);
  const byModule = new Map<string, string[]>([[web, ["createHydrator"]]]);
  for (const { module, name } of installers) {
    if (!byModule.has(module)) byModule.set(module, []);
    const names = byModule.get(module)!;
    if (!names.includes(name)) names.push(name);
  }
  const c = manifest.capabilities;
  const selected = [
    c.snapshots && "snapshots",
    c.asyncResults && "asyncResults",
    c.ssrSources.length && `ssrSources[${c.ssrSources.join(",")}]`,
    c.storeAdapters && "storeAdapters",
    c.errorMarkers && "errorMarkers",
    c.loadingMarkers && "loadingMarkers",
    c.streamLedger && "streamLedger",
    c.lazyAssets && "lazyAssets",
    c.delegatedEvents.length && `delegatedEvents[${c.delegatedEvents.join(",")}]`,
    c.resumableEvents && "resumableEvents"
  ].filter(Boolean);
  const lines = [
    "// @generated by @solidjs/web/hydration-manifest composeHydrationEntry. Do not edit.",
    `// graph: ${JSON.stringify(manifest.graph)}  producer: ${JSON.stringify(manifest.producer)}  schema: ${manifest.schema}`,
    `// capabilities: ${selected.length ? selected.join(" ") : "(none)"}`
  ];
  for (const [module, names] of byModule)
    lines.push(`import { ${names.join(", ")} } from ${JSON.stringify(module)};`);
  lines.push(
    `export const hydrate = /* @__PURE__ */ createHydrator([${installers
      .map(i => i.name)
      .join(", ")}], ${JSON.stringify(c.delegatedEvents)});`,
    ""
  );
  return lines.join("\n");
}

/**
 * The server half the manifest implies: the options for
 * `generateHydrationScript` / `<HydrationScript>`, so the bootstrap captures
 * exactly the delegated event types the client replays.
 */
export function composeServerHydrationOptions(manifest: ClientHydrationManifest): {
  eventNames: string[];
} {
  assertHydrationManifest(manifest);
  return { eventNames: [...manifest.capabilities.delegatedEvents] };
}

/** Canonical JSON for a manifest (fixed key order, 2-space indent, trailing newline). */
export function serializeHydrationManifest(manifest: ClientHydrationManifest): string {
  const c = manifest.capabilities;
  return (
    JSON.stringify(
      {
        schema: manifest.schema,
        graph: manifest.graph,
        producer: manifest.producer,
        capabilities: {
          streamLedger: c.streamLedger,
          loadingMarkers: c.loadingMarkers,
          errorMarkers: c.errorMarkers,
          asyncResults: c.asyncResults,
          storeAdapters: c.storeAdapters,
          lazyAssets: c.lazyAssets,
          delegatedEvents: c.delegatedEvents,
          ssrSources: c.ssrSources,
          snapshots: c.snapshots,
          resumableEvents: c.resumableEvents
        }
      },
      null,
      2
    ) + "\n"
  );
}
