// Generated by solid-link (@solidjs/blocks-linker) from this project's render sites.
// Do not edit; commit it. The Vite plugin regenerates it on save; `solid-link --check`
// fails when it is stale. pending / fails color the prop's reads (TypedProps<P, "Key">);
// live / static are facts for tools (a compiler may treat a static prop as inert).
// schema: solid-blocks-summary v1
export {};
declare module "@solidjs/blocks" {
  interface PropColors {
    "Container": {
      scale: { pending: false; fails: never; live: true; static: false };
      seconds: { pending: false; fails: never; live: true; static: false };
    };
    "Dot": {
      children: { pending: true; fails: import("./app").IdleError; live: true; static: false };
      s: { pending: false; fails: never; live: false; static: true };
      x: { pending: false; fails: never; live: true; static: false };
      y: { pending: false; fails: never; live: true; static: false };
    };
    "Triangle": {
      children: { pending: true; fails: import("./app").IdleError; live: true; static: false };
      s: { pending: false; fails: never; live: true; static: false };
      x: { pending: false; fails: never; live: true; static: false };
      y: { pending: false; fails: never; live: true; static: false };
    };
  }
}
