/**
 * The coverage matrix (COVERAGE.md), generated from the scenario and mode
 * registries so the documented coverage cannot drift from what runs.
 */
import { compile } from "./module.js";
import { modes, plannedModes } from "./modes.js";
import { exclusion, expectationFor } from "./register.js";
import type { Scenario } from "./types.js";

const CELL = {
  oracle: "oracle",
  equivalent: "=",
  differs: "≠ declared",
  "known-defect": "✗ defect",
  "not-applicable": "n/a"
} as const;

export function coverageMatrix(scenarios: Scenario[]): string {
  const out: string[] = [];
  const short = (id: string) =>
    id.replace("client/", "c/").replace("server/", "s/").replace("hydrate/", "h/");
  out.push("# Semantic conformance coverage");
  out.push("");
  out.push(
    "Generated by `test/conformance/conformance.spec.ts` (update with `vitest -u`). " +
      "`=` equivalent to the oracle of the same environment; `≠ declared` an intentional difference with an exact expected trace; " +
      "`✗ defect` a pinned baseline defect (must keep diverging); `n/a` not applicable; `–` not run (client-only scenario or unavailable mode)."
  );
  out.push("");
  out.push(`| scenario | ${modes.map(m => short(m.id)).join(" | ")} |`);
  out.push(`| --- | ${modes.map(() => ":-:").join(" | ")} |`);
  const notes = new Map<string, Set<string>>();
  for (const scenario of scenarios) {
    const cells = modes.map(mode => {
      const excluded = exclusion(scenario, mode);
      const expectation = expectationFor(scenario, mode);
      const runs = !excluded || expectation.status === "not-applicable";
      if (runs && expectation.status !== "equivalent") {
        const reason = "reason" in expectation ? expectation.reason : "";
        const key = `${CELL[expectation.status]}: ${reason}`;
        if (!notes.has(key)) notes.set(key, new Set());
        notes.get(key)!.add(`${scenario.name} (${mode.id})`);
      }
      if (!runs) return "–";
      if (!mode.reference) return CELL.oracle;
      return CELL[expectation.status];
    });
    out.push(`| ${scenario.name} | ${cells.join(" | ")} |`);
  }
  out.push("");
  out.push("## Declared differences, defects and exclusions");
  out.push("");
  for (const [note, where] of notes) {
    out.push(`- **${note}**`);
    out.push(`  - ${[...where].join(", ")}`);
  }
  out.push("");
  out.push("## What each generator mode actually ran (compiled output facts)");
  out.push("");
  out.push(
    "`$(` blocks left / `function*` bodies left (runtime driver) / `_$perform(` call-form operations, in the client build of the `$` source."
  );
  out.push("");
  out.push("| scenario | c/runtime | c/compiled | c/fused |");
  out.push("| --- | --- | --- | --- |");
  for (const scenario of scenarios) {
    const cells = ["client/runtime", "client/compiled", "client/fused"].map(id => {
      const mode = modes.find(m => m.id === id)!;
      try {
        const { stats } = compile(scenario.sources.generator!, mode.compile);
        return `${stats.blocks} / ${stats.generators} / ${stats.performs}`;
      } catch (error) {
        return `compile error: ${(error as Error).message.split("\n", 1)[0]}`;
      }
    });
    out.push(`| ${scenario.name} | ${cells.join(" | ")} |`);
  }
  out.push("");
  out.push("## Semantic areas");
  out.push("");
  for (const scenario of scenarios)
    out.push(`- **${scenario.name}**: ${scenario.covers.join("; ")}`);
  out.push("");
  out.push("## Planned modes (not implementable at this baseline)");
  out.push("");
  for (const planned of plannedModes)
    out.push(`- \`${planned.id}\` — ${planned.title}: ${planned.blocker}`);
  out.push("");
  return out.join("\n");
}
