// Generated by solid-link (@solidjs/blocks-linker) from this project's render sites.
// Do not edit; commit it. The Vite plugin regenerates it on save; `solid-link --check`
// fails when it is stale. pending / fails color the prop's reads (TypedProps<P, "Key">);
// live / static are facts for tools (a compiler may treat a static prop as inert).
// schema: solid-blocks-summary v1
export {};
declare module "@solidjs/blocks" {
  interface PropColors {
    "AsyncCard": {
      delay: { pending: false; fails: never; live: false; static: true };
      title: { pending: false; fails: never; live: false; static: true };
    };
    "CardBody": {
      title: { pending: false; fails: never; live: false; static: true };
      value: { pending: true; fails: never; live: true; static: false };
    };
    "Facts": {
      info: { pending: false; fails: never; live: true; static: false };
    };
    "FeedCard": {
      feed: { pending: false; fails: never; live: true; static: false };
    };
    "InnerBoundaryItem": {
      id: { pending: false; fails: never; live: false; static: true };
    };
    "Link": {
      path: { pending: false; fails: never; live: false; static: true };
    };
    "MemoList": {
      items: { pending: true; fails: unknown; live: true; static: false };
    };
    "OuterBoundaryItem": {
      id: { pending: false; fails: never; live: false; static: true };
    };
    "ProjList": {
      count: { pending: false; fails: never; live: true; static: false };
      rows: { pending: false; fails: never; live: true; static: false };
    };
    "Title": {
      item: { pending: false; fails: never; live: true; static: false };
    };
  }
}
