/**
 * Emit the linker's output: a declaration file that merges each component's
 * prop colors into `@solidjs/blocks`'s `PropColors`, keyed by the component's
 * linker key (`TypedProps<P, "Key">`). Deterministic: sorted keys, sorted
 * props, stable failure references, so the committed file only changes when
 * the facts do.
 */
import path from "node:path";

function relativeImport(fromFile, toFile) {
  let rel = path.relative(path.dirname(fromFile), toFile).split(path.sep).join("/");
  rel = rel.replace(/\.(tsx|ts|jsx|js|mts|mjs)$/, "");
  if (!rel.startsWith(".")) rel = "./" + rel;
  return rel;
}

function failsType(color, outFile) {
  if (color.failsUnknown) return "unknown";
  if (!color.fails.size) return "never";
  const parts = [...color.fails]
    .map(s => JSON.parse(s))
    .map(ref =>
      ref.global
        ? ref.global
        : ref.module
          ? `import(${JSON.stringify(ref.module)}).${ref.name}`
          : `import(${JSON.stringify(relativeImport(outFile, ref.file))}).${ref.name}`
    )
    .sort();
  return [...new Set(parts)].join(" | ");
}

export const HEADER = [
  "// Generated by solid-link (@solidjs/blocks-linker) from this project's render sites.",
  "// Do not edit; commit it. The Vite plugin regenerates it on save; `solid-link --check`",
  '// fails when it is stale. pending / fails color the prop\'s reads (TypedProps<P, "Key">);',
  "// live / static are facts for tools (a compiler may treat a static prop as inert)."
];

/**
 * @param {ReturnType<import("./solve.js").solve>} solved
 * @param {string} outFile absolute path of the generated file
 * @param {{ root: string, schemaVersion: number }} info
 */
export function emit(solved, outFile, info) {
  const byKey = new Map();
  const open = [];
  for (const c of solved.components.values()) {
    if (!c.key) continue;
    if (c.open) {
      open.push(`${c.key} (${c.why.join("; ")})`);
      continue;
    }
    if (c.callers.length === 0) continue;
    const props = byKey.get(c.key) || new Map();
    for (const [name, color] of solved.colors.get(c.id)) {
      const prev = props.get(name);
      props.set(
        name,
        prev
          ? {
              pending: prev.pending || color.pending,
              fails: new Set([...prev.fails, ...color.fails]),
              failsUnknown: prev.failsUnknown || color.failsUnknown,
              live: prev.live || color.live,
              static: prev.static && color.static
            }
          : color
      );
    }
    byKey.set(c.key, props);
  }
  const lines = [...HEADER, `// schema: solid-blocks-summary v${info.schemaVersion}`, "export {};"];
  lines.push('declare module "@solidjs/blocks" {');
  lines.push("  interface PropColors {");
  for (const key of [...byKey.keys()].sort()) {
    const props = byKey.get(key);
    lines.push(`    ${JSON.stringify(key)}: {`);
    for (const name of [...props.keys()].sort()) {
      if (name === "children") continue;
      const c = props.get(name);
      const prop = /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
      lines.push(
        `      ${prop}: { pending: ${c.pending}; fails: ${failsType(c, outFile)}; live: ${c.live}; static: ${c.static} };`
      );
    }
    lines.push("    };");
  }
  lines.push("  }");
  lines.push("}");
  if (open.length) {
    lines.push("// Open (callers not all visible; declared types kept):");
    for (const o of open.sort()) lines.push(`//   ${o}`);
  }
  return lines.join("\n") + "\n";
}
