// Generated by solid-link (@solidjs/blocks-linker) from this project's render sites.
// Do not edit; commit it. The Vite plugin regenerates it on save; `solid-link --check`
// fails when it is stale. pending / fails color the prop's reads (TypedProps<P, "Key">);
// live / static are facts for tools (a compiler may treat a static prop as inert).
// schema: solid-blocks-summary v1
export {};
declare module "@solidjs/blocks" {
  interface PropColors {
    "Footer": {
      filter: { pending: false; fails: never; live: true; static: false };
    };
    "MainSection": {
      filter: { pending: false; fails: never; live: true; static: false };
    };
    "TodoItem": {
      todo: { pending: false; fails: never; live: true; static: false };
    };
  }
}
