// Generated by solid-link (@solidjs/blocks-linker) from this project's render sites.
// Do not edit; commit it. The Vite plugin regenerates it on save; `solid-link --check`
// fails when it is stale. pending / fails color the prop's reads (TypedProps<P, "Key">);
// live / static are facts for tools (a compiler may treat a static prop as inert).
// schema: solid-blocks-summary v1
export {};
declare module "@solidjs/blocks" {
  interface PropColors {
    "Done": {
      stats: { pending: false; fails: never; live: true; static: false };
    };
    "Markdown": {
      copy: { pending: false; fails: never; live: true; static: false };
      text: { pending: false; fails: never; live: true; static: false };
    };
    "Message": {
      copy: { pending: false; fails: never; live: true; static: false };
      text: { pending: false; fails: never; live: true; static: false };
    };
    "Meter": {
      usage: { pending: false; fails: never; live: true; static: false };
    };
    "Status": {
      progress: { pending: false; fails: never; live: true; static: false };
      stats: { pending: false; fails: never; live: true; static: false };
      usage: { pending: false; fails: never; live: true; static: false };
    };
    "Ticker": {
      progress: { pending: false; fails: never; live: true; static: false };
    };
  }
}
